version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10.6

    working_directory: ~/django_rest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "apps/requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r apps/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd apps
            python3 manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports